[package]
name = "focused-window-source"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
libobs = "5.0.1"
libc = "0.2"
active-win-pos-rs = "0.9.0"
anyhow = "1.0.100"

[profile.release]
lto = true
panic = "abort"
strip = true
